modLoader = "javafml"
loaderVersion = "[40,)"
license = "GNU GPL 3.0"

[[mods]]
modId = "biome_tools"
version = "${file.jarVersion}"
displayName = "BiomeTools"
credits="Credits are on mod's page."
authors="Max094_Reikeb"
description = '''
BiomeTools is a library about biomes
'''

[[dependencies.biome_tools]] #optional
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.biome_tools]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,1.19)"
    ordering = "NONE"
    side = "BOTH"
