modLoader = "javafml"
loaderVersion = "[44,)"
license = "GNU GPL 3.0"

[[mods]]
modId = "slash_damage"
version = "${file.jarVersion}"
displayName = "Slash Damage"
credits="Credits are on mod's page."
authors="Max094_Reikeb"
description = '''
Slash Damage adds a new command to damage players
'''

[[dependencies.slash_damage]] #optional
    modId = "forge"
    mandatory = true
    versionRange = "[44,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.slash_damage]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.3,1.20)"
    ordering = "NONE"
    side = "BOTH"
